default: &default
  adapter: mysql2
  username: root
  password: toor

development:
  <<: *default
  database: hrpm_development

test:
  <<: *default
  database: hrpm_test

production:
  <<: *default
  database: hrpm_production
